# backend:
#   name: github
#   branch: master
#   repo: DaanBoertien/SimoneVanSchip

backend:
  name: git-gateway
  branch: main

media_folder: assets/img/uploads/

collections:
  - name: "content"
    label: "Teksten"
    files:
      - name: "home"
        label: "Home"
        file: "_data/home.yml"
        editor:
          preview: false
        fields:
          - label: "Titel"
            name: "title"
            widget: "string"
          - label: "Slogan"
            name: "landing-title"
            widget: "string"
          - label: "Titel service 1"
            name: "title1"
            widget: "string"
          - label: "Tekst service 1"
            name: "content1"
            widget: "text"
          - label: "Titel service 2"
            name: "title2"
            widget: "string"
          - label: "Tekst service 2"
            name: "content2"
            widget: "text"
          - label: "Titel service 3"
            name: "title3"
            widget: "string"
          - label: "Tekst service 3"
            name: "content3"
            widget: "text"
          - label: "Titel over mij"
            name: "about-title"
            widget: "string"
          - label: "Tekst over mij"
            name: "about-content"
            widget: "markdown"
          - label: "Parterns titel"
            name: "partners-title"
            widget: "string"
          - label: "Footer"
            name: "footer-text"
            widget: "string"
      - name: "contact"
        label: "Contact"
        file: "_data/contact.yml"
        editor:
          preview: false
        fields:
          - label: "Titel"
            name: "contact-title"
            widget: "string"
          - label: "Naam"
            name: "contact-name"
            widget: "string"
          - label: "Telefoonnummer"
            name: "contact-tel"
            widget: "string"
          - label: "Email"
            name: "contact-email"
            widget: "string"
          - label: "KvK"
            name: "contact-KvK"
            widget: "string"
          - label: "BTW nummer"
            name: "contact-btw"
            widget: "string"
      - name: "logos"
        label: "Logo's"
        file: "_data/logos.yml"
        editor:
          preview: false
        fields:
          - label: "Logo's"
            label_singular: "Logo"
            name: "logo"
            widget: "list"
            summary: "{{fields.alt}}"
            add_to_top: true
            fields:
              - label: "Logo"
                name: "url"
                widget: "image"
              - label: "Bedrijf"
                name: "title"
                widget: "string"
                required: false
  - name: "blog"
    label: "Portfolio"
    label_singular: "Project"
    folder: "_posts/"
    create: true
    summary: "{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "posts" }
      - { label: "PostTitel", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subtitel", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Afbeelding in post", name: "postimage", widget: "image" }
      - {
          label: "Thumbnail (portfoliopagina)",
          name: "thumbnail",
          widget: "image",
        }
